#!/usr/bin/env bash
# ============================================================
# dsec – DeepSeek Security CLI – Install Script
# ============================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║          dsec – DeepSeek Security CLI                ║"
echo "║          Installer v1.0                              ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ── Check Python 3.8+ ────────────────────────────────────────────────────────
PYTHON=$(command -v python3 || command -v python || true)
if [[ -z "$PYTHON" ]]; then
  echo "❌  Python 3 not found. Please install Python 3.8+."
  exit 1
fi
PY_VER=$("$PYTHON" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
echo "✅  Python $PY_VER found: $PYTHON"

# ── Install Python dependencies ───────────────────────────────────────────────
echo ""
echo "🔧  Installing Python dependencies…"
"$PYTHON" -m pip install -r "$SCRIPT_DIR/requirements.txt" \
  --quiet --break-system-packages 2>/dev/null \
  || "$PYTHON" -m pip install -r "$SCRIPT_DIR/requirements.txt" \
       --quiet 2>&1 | tail -5

echo "✅  Dependencies installed."

# ── Create directory structure ────────────────────────────────────────────────
echo ""
echo "🔧  Creating ~/.dsec directory structure…"
mkdir -p ~/.dsec/sessions
mkdir -p ~/.dsec/memory/chroma
echo "✅  Directories created."

# ── Initialise config ─────────────────────────────────────────────────────────
echo ""
echo "🔧  Initialising config…"
"$PYTHON" -c "import sys; sys.path.insert(0, '${SCRIPT_DIR}'); from dsec.config import init_config; init_config(); print('✅  Config initialised: ~/.dsec/config.json')"

# ── Create wrapper script (handles PYTHONPATH for symlink resolution) ─────────
WRAPPER="/usr/local/bin/dsec"

echo ""
echo "🔧  Installing global command at $WRAPPER…"

# Try sudo; if not available fall back to ~/bin
install_wrapper() {
  local target="$1"
  cat > "$target" <<WRAPPER_EOF
#!/usr/bin/env bash
# dsec wrapper – auto-generated by install.sh
export PYTHONPATH="${SCRIPT_DIR}:\${PYTHONPATH}"
exec "${PYTHON}" -m dsec "\$@"
WRAPPER_EOF
  chmod +x "$target"
}

if command -v sudo &>/dev/null && sudo -n true 2>/dev/null; then
  sudo bash -c "$(declare -f install_wrapper); install_wrapper '$WRAPPER'"
  echo "✅  Installed to $WRAPPER (via sudo)"
elif [[ -w "$(dirname "$WRAPPER")" ]]; then
  install_wrapper "$WRAPPER"
  echo "✅  Installed to $WRAPPER"
else
  # Fallback: install to ~/bin
  mkdir -p "$HOME/bin"
  install_wrapper "$HOME/bin/dsec"
  echo "✅  Installed to ~/bin/dsec"
  echo "   ⚠️   Make sure ~/bin is in your PATH:"
  echo "       export PATH=\"\$HOME/bin:\$PATH\""
  echo "   Add to ~/.bashrc or ~/.zshrc to make permanent."
fi

# ── Verify installation ───────────────────────────────────────────────────────
echo ""
echo "🔍  Verifying installation…"
if command -v dsec &>/dev/null; then
  echo "✅  'dsec' command found in PATH."
else
  echo "⚠️   'dsec' not yet in PATH. You may need to restart your shell or add the install dir to PATH."
fi

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  ✅  dsec installed successfully!                    ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  Quick start:                                        ║"
echo "║                                                      ║"
echo "║  dsec --help                                         ║"
echo "║  dsec config --set base_url http://localhost:8000    ║"
echo "║  dsec token --add YOUR_TOKEN                        ║"
echo "║  dsec --new-session htb-machine 'IP 10.10.11.23'    ║"
echo "║  dsec -q 'what port does SMB use?'                  ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
